name: Deploy Backend (SAM)

on:
  push:
    paths:
      - backend/**
      - infra/template.yaml
      - .github/workflows/deploy-backend.yml
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install SAM CLI
        run: |
          pip install aws-sam-cli

      - name: Build SAM app
        run: |
          cd infra
          sam build

      - name: Deploy SAM app
        run: |
          cd infra
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name my-app-stack --capabilities CAPABILITY_IAM --region $AWS_REGION